sudo: required
dist: bionic

language: ruby

env:
  - DOCKERFILE=tests/dockerfiles/Debian_testing.docker IMGNAME=debtest-grgsm
#  - DOCKERFILE=tests/dockerfiles/Ubuntu_16_04.docker IMGNAME=ubu16.04-grgsm
#  - DOCKERFILE=tests/dockerfiles/Ubuntu_16_04_nolibosmo.docker IMGNAME=ubu16.04-grgsm-nolibosmo
  - DOCKERFILE=tests/dockerfiles/Kali.docker IMGNAME=kali-grgsm
#  - DOCKERFILE=tests/dockerfiles/Fedora_26.Dockerfile IMGNAME=fedora26-grgsm
  - DOCKERFILE=tests/dockerfiles/Ubuntu_18_04_gnuradio_ppa.docker IMGNAME=ubuntu_18_04_gnuradio_ppa


services:
  - docker

before_install:
  - cat $DOCKERFILE > Dockerfile ; docker build -t $IMGNAME .

script:
#  - docker run -it --rm $IMGNAME sh -c 'cd /src/build;make test'
  - docker run -it --rm $IMGNAME /src/tests/scripts/decode.sh
  - docker run -it --rm $IMGNAME /src/tests/scripts/decrypt.sh
